-- DDL generated by Postico 1.5.19
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE fee (
                     id BIGSERIAL PRIMARY KEY,
                     "user" character varying(128) NOT NULL,
                     fee numeric(38,18) NOT NULL,
                     timestamp bigint NOT NULL,
                     updated_at timestamp with time zone,
                     created_at timestamp with time zone
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX fee_pkey ON fee(id int8_ops);

-- DDL generated by Postico 1.5.19
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE open_interest (
                               id BIGSERIAL PRIMARY KEY,
                               "user" character varying(128) NOT NULL,
                               perpetual_id character varying(128) NOT NULL,
                               position numeric(38,18) NOT NULL,
                               mark_price numeric(38,18) NOT NULL,
                               oi numeric(38,18) NOT NULL,
                               timestamp bigint NOT NULL,
                               updated_at timestamp with time zone,
                               created_at timestamp with time zone
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX open_interest_pkey ON open_interest(id int8_ops);
-- DDL generated by Postico 1.5.19
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE stack (
                       id BIGSERIAL PRIMARY KEY,
                       "user" character varying(128) NOT NULL,
                       stack numeric(38,18) NOT NULL,
                       timestamp bigint NOT NULL,
                       updated_at timestamp with time zone,
                       created_at timestamp with time zone
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX stack_pkey ON stack(id int8_ops);

-- DDL generated by Postico 1.5.19
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE user_info (
                           id BIGSERIAL PRIMARY KEY,
                           "user" character varying(128) NOT NULL,
                           fee numeric(38,18) NOT NULL,
                           oi numeric(38,18) NOT NULL,
                           stack numeric(38,18) NOT NULL,
                           timestamp bigint NOT NULL,
                           updated_at timestamp with time zone,
                           created_at timestamp with time zone
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX user_info_pkey ON user_info(id int8_ops);
