-- DDL generated by Postico 1.5.19
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE user_info (
                           id BIGSERIAL PRIMARY KEY,
                           trader character varying(128) NOT NULL,
                           fee numeric(38,18) NOT NULL,
                           oi numeric(38,18) NOT NULL,
                           stake numeric(38,18) NOT NULL,
                           timestamp bigint NOT NULL,
                           epoch bigint NOT NULL,
                           updated_at timestamp with time zone,
                           created_at timestamp with time zone
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX user_info_pkey ON user_info(id int8_ops);
-- DDL generated by Postico 1.5.19
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE position (
                          id BIGSERIAL PRIMARY KEY,
                          trader character varying(128) NOT NULL,
                          perpetual_add character varying(128) NOT NULL,
                          position numeric(38,18) NOT NULL,
                          mark_price numeric(38,18) NOT NULL,
                          entry_value numeric(38,18) NOT NULL,
                          timestamp bigint NOT NULL,
                          updated_at timestamp with time zone,
                          created_at timestamp with time zone
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX position_pkey ON position(id int8_ops);
-- DDL generated by Postico 1.5.19
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE fee (
                     id BIGSERIAL PRIMARY KEY,
                     trader character varying(128) NOT NULL,
                     fee numeric(38,18) NOT NULL,
                     timestamp bigint NOT NULL,
                     updated_at timestamp with time zone,
                     created_at timestamp with time zone
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX fee_pkey ON fee(id int8_ops);
-- DDL generated by Postico 1.5.19
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE stake (
                       id BIGSERIAL PRIMARY KEY,
                       trader character varying(128) NOT NULL,
                       stake numeric(38,18) NOT NULL,
                       timestamp bigint NOT NULL,
                       updated_at timestamp with time zone,
                       created_at timestamp with time zone
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX stake_pkey ON stake(id int8_ops);
